### ISSUE TITLE
Replace nominatim with something more lightweight

### ISSUE THREAD

**Issue by ellenhp** [ellenhp/headway#5]
Right now nominatim is just used as a source of truth for OSM data. Only the lookup endpoint is exposed. There's no reason we couldn't replace it with something more lightweight built on top of postgis. That could drastically reduce the memory requirements for the full Headway stack, potentially even to the point that the whole planet could be hosted with 64GB of RAM which is about the point where it becomes feasible to do.

**Comment by ellenhp** [comment]
Possibly https://github.com/digidem/osm-p2p-server ?

**Comment by clementmas** [comment]
Isn't Nominatim a requirement for the Photon geocoder? Otherwise, how do you import  the Photon Elastic Search data?

Thanks for your great work! I'm trying to set up a planet vector tile and geocoder server and what you're doing is very inspiring :)

**Comment by ellenhp** [comment]
Nominatim would still be a necessary part of photon index generation, yeah. The idea is just to save resources at runtime. I went to go check on my demo server though and while both GraphHopper and photon are using a fair bit of memory I don't see anything in `top` that would indicate nominatim is using a bunch of RAM at runtime. It's possible it's just a resource hog at build-time?

**Comment by ellenhp** [comment]
I was speaking with a friend about this over brunch and realized that nominatim supports queries that could be used to implement categorical search, which would be very useful so I'm inclined to keep it for now.

**Comment by clementmas** [comment]
I only used Photon with a pre-generated search index dump. I don't know if Nominatim runs in the background. I'm still learning how to configure all these tools.

**Comment by ellenhp** [comment]
If you've used Photon with the pre-generated index then you probably didn't have Nominatim running in the background, but Headway is currently configured to use both.

**Comment by ellenhp** [comment]
I think I'm closing this for now, because categorical search is pretty important for a maps app and nomimatim is probably the easiest way to get implement it. Photon supports query filtering by OSM tag, but it doesn't support *only* querying by OSM tag. It also requires text.
